name: Run Unit Tests and Lint Files
"on": push
env:
  FROM_PHONE_NUMBER_ID: ${{secrets.PHONE_NUMBER_ID}}
  ACCESS_TOKEN: ${{secrets.TEST_ACCESS_TOKEN}}
  TO: ${{secrets.TO}}
jobs:
  unit_test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm ci
              npm run test
